<?php

return [
    [
        'key'    => 'sales.payment_methods.phonepe',
        'name'   => 'PhonePe',
        'info'   => 'Professional PhonePe Payment Gateway for Bagisto with OAuth 2.0 Authentication. <div style="margin-top: 10px; padding: 15px; background: #f8f9ff; border: 1px solid #e3f2fd; border-radius: 8px;"><div style="display: flex; align-items: center; margin-bottom: 8px;"><span style="color: #5f259f; font-weight: 600; font-size: 14px;">🚀 PhonePe Integration</span></div><p style="margin: 0 0 10px 0; color: #424242; font-size: 13px; line-height: 1.4;">Secure payment processing with OAuth 2.0 token-based authentication. Supports UPI, Cards, Net Banking, and Wallets.</p><div style="margin-top: 10px; font-size: 12px; color: #666;"><span style="color: #4caf50;">✓</span> OAuth 2.0 Authentication</div><div style="margin-top: 4px; font-size: 12px; color: #666;"><span style="color: #4caf50;">✓</span> Multiple Payment Methods</div><div style="margin-top: 4px; font-size: 12px; color: #666;"><span style="color: #4caf50;">✓</span> Sandbox & Production Support</div><div style="margin-top: 12px; padding: 10px; background: #fff8e1; border: 1px solid #ffc107; border-radius: 6px; font-size: 12px;"><span style="color: #e65100; font-weight: 600;">⚠️ Important:</span> <span style="color: #424242;">Amount must be in paisa (₹10 = 1000 paisa). Minimum amount: ₹1 (100 paisa).</span></div></div>',
        'sort'   => 6,
        'fields' => [
            [
                'name'          => 'title',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.title',
                'type'          => 'text',
                'default_value' => 'PhonePe',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ],
            [
                'name'          => 'description',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.description',
                'type'          => 'textarea',
                'default_value' => 'Pay securely using PhonePe - UPI, Cards, Net Banking & Wallets',
                'channel_based' => true,
                'locale_based'  => true,
            ],
            [
                'name'          => 'image',
                'title'         => 'Payment Method Icon',
                'type'          => 'image',
                'channel_based' => false,
                'locale_based'  => false,
                'validation'    => 'mimes:bmp,jpeg,jpg,png,webp',
                'info'          => 'Upload an icon to display in the payment methods selection page (recommended size: 100x50px)',
            ],
            [
                'name'          => 'environment',
                'title'         => '🌍 Environment',
                'type'          => 'select',
                'validation'    => 'required',
                'options'       => [
                    [
                        'title' => 'Sandbox (Testing)',
                        'value' => 'sandbox',
                    ],
                    [
                        'title' => 'Production (Live)',
                        'value' => 'production',
                    ],
                ],
                'default_value' => 'sandbox',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Select Sandbox for testing or Production for live transactions',
            ],
            [
                'name'          => 'client_id',
                'title'         => '🔑 Client ID',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Your PhonePe Client ID from the PhonePe Business Dashboard',
            ],
            [
                'name'          => 'client_secret',
                'title'         => '🔐 Client Secret',
                'type'          => 'password',
                'validation'    => 'required',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Your PhonePe Client Secret from the PhonePe Business Dashboard (Keep this confidential)',
            ],
            [
                'name'          => 'client_version',
                'title'         => '📌 Client Version',
                'type'          => 'text',
                'default_value' => '1',
                'validation'    => 'required',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'PhonePe API Client Version (Default: 1)',
            ],
            [
                'name'          => 'checkout_type',
                'title'         => '🛒 Checkout Type',
                'type'          => 'select',
                'validation'    => 'required',
                'options'       => [
                    [
                        'title' => 'Standard',
                        'value' => 'Standard',
                    ],
                    [
                        'title' => 'Express',
                        'value' => 'Express',
                    ],
                ],
                'default_value' => 'Standard',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Select PhonePe Checkout Type (Standard is recommended for most use cases)',
            ],
            [
                'name'          => 'active',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.status',
                'type'          => 'boolean',
                'default_value' => false,
                'validation'    => 'required',
                'channel_based' => false,
                'locale_based'  => true,
            ],
        ],
    ],
];
